version: '3.8'
services:
  kitabisa-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kitabisa-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "5433:5433"
    expose:
      - "5433"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    command: -p 5433

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '5050:80' # pgAdmin dapat diakses di browser di http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: enrico@gmail.com # Ganti sesuai keinginan
      PGADMIN_DEFAULT_PASSWORD: enrico0208 # Ganti sesuai keinginan
    depends_on:
      - postgres

volumes:
  postgres:
    name: postgres-db
